version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  starwars:
    # build: .
    build: api
    container_name: "go-traefik"
    volumes:
      - .:/app
      - ../teraform:/teraform
    # image: go-traefik:latest              # manual build testing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.starwars.rule=PathPrefix(`/movies`)"
      - "traefik.http.services.starwars.loadbalancer.server.port=3000"
